#pragma once
#ifndef TOKEN_H
#define TOKEN_H

#include <string>


enum TokenType {
    TOKEN_PROGRAM, TOKEN_BEGIN, TOKEN_END, TOKEN_IF, TOKEN_FI, TOKEN_THEN, TOKEN_ELSE, TOKEN_WHILE, TOKEN_DO, TOKEN_DONE,
    TOKEN_VAR, TOKEN_PRINT, TOKEN_IDENTIFIER, TOKEN_NUMBER, TOKEN_ASSIGN, TOKEN_PLUS, TOKEN_MINUS, TOKEN_MULTIPLY,
    TOKEN_DIVIDE, TOKEN_EQUAL, TOKEN_LESS, TOKEN_GREATER, TOKEN_LPAREN, TOKEN_RPAREN,
    TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_DOT, TOKEN_EOF,
    TOKEN_AND, TOKEN_OR, TOKEN_NOT  
};
// Token 结构体
struct Token {
    TokenType type;  // Token 类型
    std::string value;  // Token 值
};

#endif