# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/VIVADO_Project/project_yxn/project_yxn.srcs/sources_1/ip/immg/immg.xci
# IP: The module: 'immg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/VIVADO_Project/project_yxn/project_yxn.srcs/sources_1/ip/immg/immg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'immg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/VIVADO_Project/project_yxn/project_yxn.srcs/sources_1/ip/immg/immg.xci
# IP: The module: 'immg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/VIVADO_Project/project_yxn/project_yxn.srcs/sources_1/ip/immg/immg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'immg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
